name: reqresz
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.5
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_markdown: ^0.7.6+2

  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.3

  # Network & APIs
  dio: ^5.4.1
  connectivity_plus: ^6.1.3

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

  # Utils
  dartz: ^0.10.1
  intl: ^0.20.2
  logger: ^2.0.2+1
  fluttertoast: ^8.2.2
  sizer: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/